---
- hosts: localhost
  become: true 
  tasks: 

    - name: Create Repo
      command: curl https://packages.microsoft.com/config/rhel/8/prod.repo > /etc/yum.repos.d/mssql-release.repo
    
    - ansible.builtin.yum:
        name: sqlcmd
        state: installed 
      
    - azure_rm_resourcegroup: 
        location: "{{location}}"
        name: "{{resourcegroup}}"
      name: "Create Azure resource group"
     
    - azure_rm_sqlserver: 
        admin_password: "{{password}}"
        admin_username: "{{admin}}"
        name: "{{sqlserver}}"
        resource_group: "{{resourcegroup}}"
        version: "12.0"
      name: "Create Azure SQL Server Logical host"
    - azure_rm_sqldatabase: 
        name: "{{sqldb}}"
        resource_group: "{{resourcegroup}}"
        server_name: "{{sqlserver}}"
      name: "Create Azure SQL Database"
    - name: Configure Azure SQL Server firewall
      azure_rm_sqlfirewallrule:
        resource_group: "{{resourcegroup}}"
        server_name: "{{sqlserver}}"
        name: 'Allow_Specific_Range'
        start_ip_address: '15.0.0.1' # start of your allowed IP range
        end_ip_address: '15.0.0.255' # end of your allowed IP range
      register: firewall_result
    - debug:
        var: firewall_result
    - name: Create contained user mapped to Azure AD identity
      command: >
       sqlcmd -S {{ sqlserver }}.database.windows.net 
              -d {{ manulife_db }} 
              -U {{ admin }} 
              -P {{ password }} 
              -Q "CREATE USER [{{ azure_ad_username }}] FROM EXTERNAL PROVIDER;"
      register: result
    - name: Display result
      debug:
       var: result.stdout_lines 

        

  vars: 
    admin: student
    location: eastus
    password: "RedHat123@!"
    resourcegroup: manulife_test_1
    sqldb: manulife_db  
    sqlserver: manulifesqlserver
    azure_ad_username: alex
