---
- hosts: localhost
  become: true 
  ignore_errors: true 
  tasks: 
      
    - azure_rm_resourcegroup: 
        location: "{{location}}"
        name: "{{resourcegroup}}"
      name: "Create Azure resource group"
     
    - azure_rm_sqlserver: 
        admin_password: "{{password}}"
        admin_username: "{{admin}}"
        name: "{{sqlserver}}"
        resource_group: "{{resourcegroup}}"
        version: "12.0"
      name: "Create Azure SQL Server Logical host"
    - azure_rm_sqldatabase: 
        name: "{{sqldb}}"
        resource_group: "{{resourcegroup}}"
        server_name: "{{sqlserver}}"
      name: "Create Azure SQL Database"
    - name: Configure Azure SQL Server firewall
      azure_rm_sqlfirewallrule:
        resource_group: "{{resourcegroup}}"
        server_name: "{{sqlserver}}"
        name: 'Allow_Specific_Range'
        start_ip_address: '15.0.0.1' # start of your allowed IP range
        end_ip_address: '15.0.0.255' # end of your allowed IP range
      register: firewall_result
    - debug:
        var: firewall_result
       # Create a private endpoint
       
    - name: Create private endpoint
      azure_rm_privateendpoint:
       name: testprivateendpoint
       resource_group: "{{ resourcegroup }}"
       private_link_service_connections:
         - name: Test_private_link_service
           private_link_service_id: /subscriptions/6d1e140e-296e-42c1-b27a-26c101cc127f/resourceGroups/manulife_test_1/providers/Microsoft.Network/privateLinkServices/testervice
       subnet:
           id: /subscriptions/6d1e140e-296e-42c1-b27a-26c101cc127f/resourceGroups/manulife_test_1/providers/Microsoft.Network/virtualNetworks/fredvnet/subnets/default

    # Associate private endpoint with DNS zone
    - name: Create a private DNS zone link
      azure.azcollection.azure_rm_privatednszonelink:
        resource_group: "{{ resourcegroup }}"
        zone_name: privatelink.database.windows.net
        name: manulifezone
        virtual_network: manulifenw
        registration_enabled: yes
        etag: your_etag    

  vars: 
    admin: student
    location: eastus
    password: "RedHat123@!"
    resourcegroup: manulife_test_1
    sqldb: manulife_db  
    sqlserver: manulifesqlserver
    azure_ad_username: alex
    your_subscription_id: 6d1e140e-296e-42c1-b27a-26c101cc127f
