---
- hosts: localhost
  become: true 
  tasks:
  
    - copy:
        src: sqlcmd
        dest: /usr/local/bin/

    - name: Test sqlcmd
      shell: sqlcmd --version
      register: version
    
    - name: Print the version
      debug: 
        var: version        
  
